### ISSUE TITLE
Version 2 does not work with Node.js v15

### ISSUE THREAD

**Issue by bennycode** [infctr/eslint-plugin-typescript-sort-keys#45]
I wanted to upgrade from eslint-plugin-typescript-sort-keys v1.8.0 to v2.0.0 but it fails in my CI environment using Node.js v15.14.0 with the following message:

> error @typescript-eslint/experimental-utils@5.3.1: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.14.0"

Can you downgrade `@typescript-eslint/experimental-utils` to make it work again?

**Comment by infctr** [comment]
Downgrading `@typescript-eslint/experimental-utils` would require that you additionally install an older version of `@typescript-eslint/typescript-estree` that doesn't make any sense. This was an issue fixed in #38 
As v2.0.0 is a breaking change you shouldn't update and stay an older version. Or update to latest node
